apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ozb
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/ozb.git
    path: kubernetes
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: ozb
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
