apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ozbargain
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/ozb.git
    path: kubernetes
    kustomize:
      images:
        - ozb-discord-bot=ghcr.io/accurate0/ozb-discord-bot:${ARGOCD_APP_REVISION}
        - ozb-trigger=ghcr.io/accurate0/ozb-trigger:${ARGOCD_APP_REVISION}
        - ozb-finder=ghcr.io/accurate0/ozb-finder:${ARGOCD_APP_REVISION}
        - ozb-migration=ghcr.io/accurate0/ozb-migration:${ARGOCD_APP_REVISION}

  destination:
    server: https://kubernetes.default.svc
    namespace: ozbargain
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
