[package]
name = "ozb"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
fern = "0.6.2"
futures = "0.3.28"
log = "0.4.20"
serde = "1.0.183"
tokio = { version = "1.32.0", features = ["rt", "macros", "rt-multi-thread"] }
twilight-cache-inmemory = "0.15.2"
twilight-gateway = "0.15"
twilight-http = "0.15"
openssl = { version = "0.10", features = ["vendored"] }
twilight-model = "0.15"
twilight-standby = "0.15"
twilight-util = { version = "0.15.2", features = ["builder"] }
reqwest = { version = "0.11.18", features = ["json", "gzip"] }
reqwest-middleware = "0.2.3"
reqwest-tracing = "0.4.5"
reqwest-retry = "0.2.2"
http = "0.2.9"
serde_json = "1.0.105"
zephyrus = "0.10.0"
redis = { version = "0.23.2", features = [
    "aio",
    "tokio-comp",
    "tokio-rustls-comp",
    "connection-manager",
] }
aws-sdk-secretsmanager = "0.29.0"
aws-sdk-dynamodb = "0.29.0"
serde_dynamo = { version = "4.2.4", features = ["aws-sdk-dynamodb+0_24"] }
tracing = "0.1.37"
config = "0.13.3"
rss = "2.0.6"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.9", features = [
    "mongodb",
] }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.9", features = [
    "mongodb",
] }
chrono = "0.4.26"
lambda_runtime = "0.8.1"
lambda_http = "0.8.1"
chrono-tz = "0.8.3"
tl = "0.7.7"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25"
uuid = { version = "1.4.1", features = ["v4"] }
async-trait = "0.1.73"
aws-config = "0.56.0"


[features]
prisma = []

[[bin]]
name = "ozb"
path = "src/bin/ozb.rs"
required-features = ["prisma"]

[[bin]]
name = "trigger"
path = "src/bin/trigger.rs"
required-features = ["prisma"]

[[bin]]
name = "timed"
path = "src/bin/timed.rs"
required-features = ["prisma"]

[[bin]]
name = "daemon"
path = "src/bin/daemon.rs"
required-features = ["prisma"]

[[bin]]
name = "prisma"
path = "src/bin/prisma.rs"

[lib]
name = "ozb"
path = "src/lib.rs"

[profile.release-strip]
inherits = "release"
strip = "symbols"
