[package]
name = "ozb"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
fern = "0.6.2"
futures = "0.3.27"
log = "0.4.17"
serde = "1.0.158"
tokio = { version = "1.26.0", features = ["rt", "macros", "rt-multi-thread"] }
twilight-cache-inmemory = "0.15"
twilight-gateway = "0.15"
twilight-http = "0.15"
openssl = { version = "0.10", features = ["vendored"] }
twilight-model = "0.15"
twilight-util = { version = "0.15.1", features = ["builder"] }
reqwest = { version = "0.11.15", features = ["json", "gzip"] }
reqwest-middleware = "0.2.1"
reqwest-tracing = "0.4.1"
reqwest-retry = "0.2.2"
http = "0.2.9"
serde_json = "1.0.94"
foundation = { git = "https://github.com/Accurate0/foundation.git" }
zephyrus = "0.9.0"
redis = { version = "0.22.3", features = ["aio", "tokio-comp"] }
aws-sdk-secretsmanager = "0.24.0"
aws-sdk-dynamodb = "0.24.0"
serde_dynamo = { version = "4.1.0", features = ["aws-sdk-dynamodb+0_24"] }
tracing = "0.1.37"
config = "0.13.3"
rss = "2.0.2"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.6", features = ["mongodb"] }
chrono = "0.4.24"
lambda_runtime = "0.7.3"
lambda_http = "0.7.3"
chrono-tz = "0.8.1"

[[bin]]
name = "ozb"
path = "src/bin/ozb.rs"

[[bin]]
name = "trigger"
path = "src/bin/trigger.rs"

[lib]
name = "ozb"
path = "src/lib.rs"

[workspace]
members = [
    "prisma-cli",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"
