apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozb
  namespace: ozb
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: ozb
  replicas: 1
  template:
    metadata:
      labels:
        app: ozb
    spec:
      tolerations:
        - key: "group"
          operator: "Equal"
          value: "external"
          effect: "NoSchedule"
      containers:
        - name: ozb
          image: ghcr.io/accurate0/ozb-bot:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ozb-managed-secrets
