apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozb-discord-bot
  namespace: ozbargain
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: ozb-discord-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: ozb-discord-bot
    spec:
      initContainers:
        - name: ozb-migration
          image: ozb-migration:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ozb-managed-secrets

      containers:
        - name: ozb-discord-bot
          image: ozb-discord-bot:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ozb-managed-secrets
