name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        apps: [discord-bot, finder, trigger]

    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: .
      image-name: ozb-${{ matrix.apps }}
      docker-build-args: |
        BINARY_NAME=ozb-${{ matrix.apps }}
      use-rust-caching: true

  deploy:
    needs: build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s.yaml@main
    with:
      application-name: ozbargain
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
