name: Clean up old images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old images

    permissions:
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch multi-platform package version SHAs
        id: multi-arch-digests
        run: |
          bot=$(docker manifest inspect ghcr.io/accurate0/ozb-discord-bot | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
          finder=$(docker manifest inspect ghcr.io/accurate0/ozb-finder | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
          trigger=$(docker manifest inspect ghcr.io/accurate0/ozb-trigger | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
          migration=$(docker manifest inspect ghcr.io/accurate0/ozb-migration | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
          echo "multi-arch-digests=$bot,$finder,$trigger,$migration" >> $GITHUB_OUTPUT

      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "ozb-discord-bot ozb-finder ozb-trigger ozb-migration"
          image-tags: "!latest"
          keep-n-most-recent: 10
          cut-off: 3d
          skip-shas: ${{ steps.multi-arch-digests.outputs.multi-arch-digests }}
