name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: install musl gcc
        run: sudo apt install musl-tools

      - uses: actions/checkout@v3
      - uses: Accurate0/rust-toolchain@main
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: generate prisma client
        run: cargo run --locked --profile release-strip --target x86_64-unknown-linux-musl --bin prisma -- generate

      - name: cargo build
        run: cargo build --locked --profile release-strip --target x86_64-unknown-linux-musl --features="prisma" --bin trigger --bin timed --bin daemon

      - name: copy artifacts
        run: |
          mkdir ./ozb
          cp ./target/x86_64-unknown-linux-musl/release-strip/trigger ./ozb/Trigger
          cp ./target/x86_64-unknown-linux-musl/release-strip/timed ./ozb/Timed
          cp ./target/x86_64-unknown-linux-musl/release-strip/daemon ./ozb/Daemon

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ozb
          path: ./ozb

  deploy-lambda:
    permissions:
      id-token: write
    needs: [build-lambda]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - Trigger

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: ozb

      - name: create zip
        run: |
          mv ./${{ matrix.task }} ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: deploy ${{ matrix.task }}
        run: aws lambda update-function-code --function-name Ozb-${{ matrix.task }} --zip-file fileb://bootstrap.zip --region ${{ vars.AWS_REGION }}
