name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/ozb

  deploy-ecs:
    runs-on: ubuntu-latest
    needs: [build-container, build-lambda]
    steps:
      - name: deploy container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws ecs update-service --region ap-southeast-2 --cluster default-cluster --service ozb-service --force-new-deployment 2>&1 1>/dev/null

  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: install musl gcc
        run: sudo apt install musl-tools

      - uses: actions/checkout@v3
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-v2

      - name: generate prisma client
        run: cargo run --locked --profile release-strip --target x86_64-unknown-linux-musl --bin prisma -- generate

      - name: cargo build
        run: cargo build --locked --profile release-strip --target x86_64-unknown-linux-musl --features="prisma" --bin trigger --bin timed

      - name: copy artifacts
        run: |
          mkdir ./ozb
          cp ./target/x86_64-unknown-linux-musl/release-strip/trigger ./ozb/Trigger
          cp ./target/x86_64-unknown-linux-musl/release-strip/timed ./ozb/Timed

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ozb
          path: ./ozb

  deploy-lambda:
    needs: [build-lambda, deploy-ecs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - Trigger
          - Timed

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ozb

      - name: create zip
        run: |
          mv ./${{ matrix.task }} ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: deploy ${{ matrix.task }}
        run: aws lambda update-function-code --function-name Ozb-${{ matrix.task }} --zip-file fileb://bootstrap.zip --region ap-southeast-2
